### ISSUE TITLE
Version numbering in version.h is not convenient

### ISSUE THREAD

**Issue by prozumr** [prozumr/RLOTTO2#11]
Versioning numbering in source code is not convenient. A simplified concept is required to maintain version numbers in the source code only once.  In addition a more consistent guideline is required how to increment the component of full version number.

**Comment by mabod** [comment]
What about doing release tagging with github? [https://help.github.com/articles/creating-releases/](https://help.github.com/articles/creating-releases/) or with the git commandline [https://git-scm.com/book/en/v2/Git-Basics-Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging
)

The release tag can be evaluated by the make command and then be added to the executable during compile time like this:
`gcc -DMYSTRING='"hello"' ...`

This is similar to saying 
`#define MYSTRING "hello" `
in the code. [https://www.rapidtables.com/code/linux/gcc/gcc-d.html
](https://www.rapidtables.com/code/linux/gcc/gcc-d.html
)

**Comment by prozumr** [comment]
Thanks for the hint mabod. I need to study your references and think about it. I have not yet defined or decided for the best concept of versioning, i.e version numbers. I guess what I am looking for is [semantic versioning](https://semver.org/). Not sure if this can be realized or combined with your proposal. So what I am looking for is:

1. A unique version number
2. Version number included in the code, i.e the version number is visible finally in the binary
3. A concept (with strict formalzed rules) with components in the version number that reflects major/minor releases and eventually a build number
4. Mapping of version number to github commit/release must be possible
5. Easy maintanance of the version number

That's being sad I need to study this subject first a little bit including your proposal.

**Comment by prozumr** [comment]
Resolved by v0.9.0-beta. See also attached documentation for versioning rules and implementation approach.

[Versioning Conventions.pdf](https://github.com/prozumr/RLOTTO2/files/1864458/Versioning.Conventions.pdf)
