### ISSUE TITLE
Makefile for Linux needed

### ISSUE THREAD

**Issue by prozumr** [prozumr/RLOTTO2#12]
Makefile needed in order  to compile the source code for Linux. Plese add to the source files on github.

**Comment by mabod** [comment]
First simple Makefile added with commit f9347e1af3d600b32ce3b25aa413a11d887986b5

**Comment by prozumr** [comment]
Thank you mabod! -- Just a question and forgive me my limited understanding: Is the concept of makefiles for Linux platform only or can it be used everywhere where you use a compiler, respectively the GNU Compiler? In the second case an additional question would be: can your version of the makefile also used for other platforms, like windows?

**Comment by mabod** [comment]
In theory Makefiles can work everywhere. First you need "`make`" for Windows: http://gnuwin32.sourceforge.net/packages/make.htm

make can be executed directly out of Visual Studio: 
https://msdn.microsoft.com/de-de/library/aa265200(v=vs.60).aspx
or Visual Studio Code: 
https://blogs.msdn.microsoft.com/vcblog/2016/10/24/building-your-c-application-with-visual-studio-code/


Scond you need a Makefile which is distinguishing between Linux and Windows. This is the tricky part: http://skramm.blogspot.de/2013/04/writing-portable-makefiles.html
https://stackoverflow.com/questions/4058840/makefile-that-distincts-between-windows-and-unix-like-systems

**Comment by prozumr** [comment]
Thanks for explanation. Not needed for other platforms at this time. I was just curious. In any case this issue can successfull be regarded as "Closed".
